name: internship_ai_weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  # State management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with Bloc)
  freezed_annotation: ^2.4.1
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0
  # Easily create beautify toast with a series of animations and make toast more beautiful.
  flutter_styled_toast: ^2.2.1
  # Simple direct Service Locator that allows to access the concrete implementation from everywhere
  get_it: ^7.7.0
  # Dart library that checks for internet
  internet_connection_checker: ^2.0.0
  # Provides API to store data in secure storage
  flutter_secure_storage: ^9.2.2
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  # For Beautiful animations 
  animate_do: ^3.3.4
  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  # Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
  # Mapping
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.12
  # Recommended lints to encourage good coding practices
  flutter_lints: ^4.0.0
  # Code generator (mainly used with Bloc)
  freezed: ^2.5.2
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  # Code generator for retrofit
  retrofit_generator: ^9.1.2
  # Performs static analysis of Dart code. It is useful for tool integration and embedding.
  analyzer: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900


flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/utils/
  filename: app_assets.dart
  field_prefix: null