// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKoB2cFDneducbUfIgMr6AgVhDHe8wGk',
    appId: '1:712411863933:web:7a6b5e31ecd84e1cc18a14',
    messagingSenderId: '712411863933',
    projectId: 'cellula-internship',
    authDomain: 'cellula-internship.firebaseapp.com',
    storageBucket: 'cellula-internship.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfHqrBXwoTfvNro7B_XOpMfx0BtOn0Fk',
    appId: '1:712411863933:android:6f06c0d962511dedc18a14',
    messagingSenderId: '712411863933',
    projectId: 'cellula-internship',
    storageBucket: 'cellula-internship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHt-cxkyU_n8NLeoBAb9YCMAuVbqwF1fA',
    appId: '1:712411863933:ios:1119031fcd58ffb6c18a14',
    messagingSenderId: '712411863933',
    projectId: 'cellula-internship',
    storageBucket: 'cellula-internship.appspot.com',
    iosBundleId: 'com.example.internshipAiWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHt-cxkyU_n8NLeoBAb9YCMAuVbqwF1fA',
    appId: '1:712411863933:ios:1119031fcd58ffb6c18a14',
    messagingSenderId: '712411863933',
    projectId: 'cellula-internship',
    storageBucket: 'cellula-internship.appspot.com',
    iosBundleId: 'com.example.internshipAiWeatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtKoB2cFDneducbUfIgMr6AgVhDHe8wGk',
    appId: '1:712411863933:web:cb012167fe5dd6eac18a14',
    messagingSenderId: '712411863933',
    projectId: 'cellula-internship',
    authDomain: 'cellula-internship.firebaseapp.com',
    storageBucket: 'cellula-internship.appspot.com',
  );
}
