// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnwzvfxNpg-R0BxQK1m4zjtnnNyxaG8Lc',
    appId: '1:815246154921:web:7e5232092a234b086b9db8',
    messagingSenderId: '815246154921',
    projectId: 'cellula-internship-1a146',
    authDomain: 'cellula-internship-1a146.firebaseapp.com',
    storageBucket: 'cellula-internship-1a146.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDEj3JF24btP8pduXraV7er7rl5Phpx0',
    appId: '1:815246154921:android:3c909f5315f74d656b9db8',
    messagingSenderId: '815246154921',
    projectId: 'cellula-internship-1a146',
    storageBucket: 'cellula-internship-1a146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcrhbfmbSdVYPTblTVI3HZQEjvt-t22k',
    appId: '1:815246154921:ios:1172b99f32b1b6be6b9db8',
    messagingSenderId: '815246154921',
    projectId: 'cellula-internship-1a146',
    storageBucket: 'cellula-internship-1a146.appspot.com',
    iosBundleId: 'com.example.internshipAiWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxcrhbfmbSdVYPTblTVI3HZQEjvt-t22k',
    appId: '1:815246154921:ios:1172b99f32b1b6be6b9db8',
    messagingSenderId: '815246154921',
    projectId: 'cellula-internship-1a146',
    storageBucket: 'cellula-internship-1a146.appspot.com',
    iosBundleId: 'com.example.internshipAiWeatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnwzvfxNpg-R0BxQK1m4zjtnnNyxaG8Lc',
    appId: '1:815246154921:web:a0c89e8a586124e16b9db8',
    messagingSenderId: '815246154921',
    projectId: 'cellula-internship-1a146',
    authDomain: 'cellula-internship-1a146.firebaseapp.com',
    storageBucket: 'cellula-internship-1a146.appspot.com',
  );
}
